config/routes.rb
Rails.application.routes.draw do
  resources :accounts
  root to: "accounts#index"
end

app/models/account.rb
class Account < ApplicationRecord
  has_secure_password

  validates :email, presence: true, uniqueness: true, format: URI::MailTo::EMAIL_REGEXP
  validates :login, presence: true, uniqueness: true
  validates :name, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: [:show, :edit, :update, :destroy]

  # GET /accounts
  def index
    @accounts = Account.all
    @account = Account.new
  end

  # GET /accounts/1
  def show
  end

  # GET /accounts/new
  def new
    @account = Account.new
  end

  # GET /accounts/1/edit
  def edit
  end

  # POST /accounts
  def create
    @account = Account.new(account_params)

    respond_to do |format|
      if @account.save
        format.json { render json: @account, notice: 'Account was successfully created.', status: :ok }

      else
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounts/1
  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to @account, notice: 'Account was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /accounts/1
  def destroy
    @account.destroy
    respond_to do |format|
      format.html { redirect_to accounts_url, notice: 'Account was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def account_params
      params.require(:account).permit(:name, :login, :email, :password, :password_confirmation)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/accounts/_form.html.erb
<%= form_with(model: @account, local: false, id: "newAccountForm", class: "", :html => { :role => "form" }) do |form| %>
  <div id="error_explanation" class="text-danger"></div>
  <div class="form-group col-12">
    <span class="text-danger">*</span><%= form.label :name, :class => 'form-label' %>
    <%= form.text_field :name, :class => 'form-control' %>
  </div>
  <div class="form-group col-12">
    <span class="text-danger">*</span><%= form.label :login, :class => 'form-label' %>
    <%= form.text_field :login, :class => 'form-control' %>
  </div>
  <div class="form-group col-12">
    <span class="text-danger">*</span><%= form.label :email, :class => 'form-label' %>
    <%= form.text_field :email, :class => 'form-control' %>
  </div>
  <div class="form-group col-12">
    <span class="text-danger">*</span><%= form.label :password, :class => 'form-label' %>
    <%= form.password_field :password, :class => 'form-control' %>
  </div>
  <div class="form-group col-12">
    <span class="text-danger">*</span><%= form.label :password_confirmation, :class => 'form-label' %>
    <%= form.password_field :password_confirmation, :class => 'form-control' %>
  </div>
  <div class="col-12">
    <%= form.submit :class => 'btn btn-primary', :id => 'submit-form-btn' %>
  </div>
<% end %>

app/views/accounts/_modal.html.erb
<div id="modal-window" class="modal fade" tabindex="-1" data-bs-backdrop="static" role="dialog" aria-labelledby="modalWindowLabel" aria-hidden="true">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
		    <div class="modal-header">
		      <h4 class="modal-title" id="newAccountLabel">New Account</h4>
		      <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
		    </div>
	    	<div class="modal-body"></div>
		</div>
	</div>
</div>

app/views/accounts/create.js.erb
$('#modal-window').modal('toggle');

app/views/accounts/edit.html.erb
<h1>Editing Account</h1>

<%= render 'form', account: @account %>

<%= link_to 'Back', @account %> |
<%= link_to 'Accounts', accounts_path %>

app/views/accounts/index.html.erb
<div class="page">
  <% if !notice.nil? %>
      <p id="notice"><%= notice %></p>
  <% end %>
  <h1>Accounts</h1>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Name</th>
        <th>Email</th>
      </tr>
    </thead>
    <tbody>
      <% @accounts.each do |account| %>
        <tr>
          <td><%= link_to account.name, account %></td>
          <td><%= mail_to account.email %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <br>
  <%= link_to 'New Account', new_account_path, {:remote => true, 'data-bs-toggle' =>  "modal", 'data-bs-target' => '#modal-window', class: 'btn btn-primary btn-lg modal-btn'} %>
  <%= render 'modal' %>
</div>

app/views/accounts/new.js.erb
// Render the new form
$('.modal-body').html('<%= j (render "form") %>');
 
// Show the dynamic dialog
$('#modal-window').modal("show");
 
// Set focus to the first element
$('#modal-window').on('shown.bs.modal', function () {
	$('#account_name').focus();
});

app/views/accounts/show.html.erb
<div class=page>
	<% if !notice.nil? %>
	    <p id="notice"><%= notice %></p>
	<% end %>
  <h1>Account for <%= @account.name %></h1>
	<p>
	  <strong>Name:</strong>
	  <%= @account.name %>
	</p>
	<p>
	  <strong>Login:</strong>
	  <%= @account.login %>
	</p>
	<p>
	  <strong>Email:</strong>
	  <%= mail_to @account.email %>
	</p>
	<%= link_to 'Edit', edit_account_path(@account) %> |
	<%= link_to 'Destroy', @account, method: :delete, data: { confirm: 'Are you sure?' } %> |
	<%= link_to 'Accounts', accounts_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ExampleCom</title>
    <meta charset="utf-8" name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body class="container">
    <%= yield %>
  </body>
</html>